### PR TITLE
Server side encryption

### LINKED ISSUE #9: Upload to S3 with SSE
In my organization, uploading using SSE (server side encryption) is enforced through bucket policies. It looks like in <code>writeBackupRemote</code> there is no option to specify SSE.

<code>https://github.com/pshima/consul-snapshot/blob/master/backup/backup.go#L300-L327</code>.

```go
func (b *Backup) writeBackupRemote() {
	s3Conn := session.New(&aws.Config{Region: aws.String(string(b.Config.S3Region))})

	t := time.Unix(b.StartTime, 0)
	remotePath := fmt.Sprintf("backups/%v/%d/%v/%v", t.Year(), t.Month(), t.Day(), filepath.Base(b.FullFilename))

	b.RemoteFilePath = remotePath

	// re-read the compressed file.  There is probably a better way to do this
	localFileContents, err := ioutil.ReadFile(b.FullFilename)
	if err != nil {
		log.Fatalf("[ERR] Could not read compressed file!: %v", err)
	}

	// Create the params to pass into the actual uploader
	params := &s3manager.UploadInput{
		Bucket: &b.Config.S3Bucket,
		Key:    &b.RemoteFilePath,
		Body:   bytes.NewReader(localFileContents),
	}

	log.Printf("[INFO] Uploading %v/%v to S3 in %v", string(b.Config.S3Bucket), b.RemoteFilePath, string(b.Config.S3Region))
	uploader := s3manager.NewUploader(s3Conn)
	_, err = uploader.Upload(params)
	if err != nil {
		log.Fatalf("[ERR] Could not upload to S3!: %v", err)
	}
}
```

What would be the cleanest way to add this option? Would it just be easiest to add another environment variable and check to see if it's set?

### PR DESCRIPTION
**Pull request by mfischer-zd**
As noted in commit comments. 

Closes #9

### CODE REVIEW

**Comment by pshima** [comment]
This is awesome thanks for adding this @mfischer-zd (and for fixing the acceptance test filename).

Looks pretty straight forward, let me check a couple things (not sure how it reacts when those options are empty strings).

Also I need to check that the GetObjectInput doesn't need the SSE bits here: https://github.com/pshima/consul-snapshot/blob/master/restore/restore.go#L129  It seems like the API comments on get might be wrong via https://github.com/aws/aws-sdk-go/blob/master/service/s3/api.go#L5518

If all is well I will merge and cut a release.

**Comment by mfischer-zd** [comment]
>  I need to check that the GetObjectInput doesn't need the SSE bits

That's only necessary if a Customer Key is supplied.  This patch doesn't provide such functionality, though it might be useful down the road.

**Comment by pshima** [comment]
Excellent, great.  Will take a closer look as soon as I am able.

**Comment by mfischer-zd** [comment]
Also, before you cut a release, I'd like to address #11.

**Pull request merged**
